// Original "Closest number wins" questions for Brain Brawl. Well-established facts with whole-number answers.
// { q, a, year?: true (no thousands separator), unit?: shown after the number }
export default [
  // Science & nature
  { q: 'How many bones are in the adult human body?', a: 206 },
  { q: 'How many teeth does an adult human have, including wisdom teeth?', a: 32 },
  { q: 'How many chromosomes are in a typical human body cell?', a: 46 },
  { q: 'How many hearts does an octopus have?', a: 3 },
  { q: 'How many legs does a lobster have, including its claws?', a: 10 },
  { q: 'How many elements are on the periodic table (as of 2016)?', a: 118 },
  { q: 'At sea level, what is the boiling point of water in degrees Fahrenheit?', a: 212, unit: '°F' },
  { q: 'How many Earth days does it take Mars to orbit the Sun?', a: 687, unit: 'days' },
  { q: 'What is the average distance from the Earth to the Moon, in kilometres?', a: 384400, unit: 'km' },
  { q: 'Roughly how many minutes does sunlight take to reach the Earth?', a: 8, unit: 'min' },
  { q: 'What is the speed of light in a vacuum, in km per second, rounded to the nearest thousand?', a: 300000, unit: 'km/s' },
  { q: 'How many vertebrae are in a typical human spine, counting the fused ones?', a: 33 },
  { q: 'How many bones are in one human hand, including the wrist?', a: 27 },
  { q: 'How many teeth does a typical adult dog have?', a: 42 },
  { q: 'What is the speed of sound in air at 20 °C, in metres per second?', a: 343, unit: 'm/s' },
  { q: 'How many moons does Mars have?', a: 2 },
  { q: 'In what year was Pluto reclassified as a dwarf planet?', a: 2006, year: true },
  { q: "What is the Earth's circumference at the equator, in kilometres?", a: 40075, unit: 'km' },
  { q: 'At sea level, water boils at what temperature in kelvin (rounded)?', a: 373, unit: 'K' },
  { q: 'How many bones make up the human skull?', a: 22 },
  { q: "In what year did Charles Darwin publish 'On the Origin of Species'?", a: 1859, year: true },
  { q: 'How many Earth years does Jupiter take to orbit the Sun (rounded)?', a: 12, unit: 'years' },
  { q: 'In what year was the Hubble Space Telescope launched?', a: 1990, year: true },
  { q: 'How many km/h is 100 miles per hour (rounded)?', a: 161, unit: 'km/h' },
  { q: 'How many legs does an insect have?', a: 6 },
  { q: 'How many bones are in the human foot (including the ankle)?', a: 26 },

  // History
  { q: 'In what year did the Titanic sink?', a: 1912, year: true },
  { q: 'In what year did the Berlin Wall fall?', a: 1989, year: true },
  { q: 'In what year did humans first walk on the Moon?', a: 1969, year: true },
  { q: 'In what year did World War II end?', a: 1945, year: true },
  { q: 'In what year did Columbus first reach the Americas?', a: 1492, year: true },
  { q: 'In what year did the French Revolution begin?', a: 1789, year: true },
  { q: 'In what year was the Battle of Hastings fought?', a: 1066, year: true },
  { q: 'In what year did the Great Fire of London happen?', a: 1666, year: true },
  { q: 'In what year was the Magna Carta sealed?', a: 1215, year: true },
  { q: "How many years did the Hundred Years' War actually last?", a: 116, unit: 'years' },
  { q: 'In what year did the Wright brothers make their first powered flight?', a: 1903, year: true },
  { q: 'In what year was Nelson Mandela released from prison?', a: 1990, year: true },
  { q: 'In what year did the Soviet Union dissolve?', a: 1991, year: true },
  { q: 'In what year was the US Declaration of Independence adopted?', a: 1776, year: true },
  { q: 'In what year did the Wall Street Crash happen?', a: 1929, year: true },
  { q: 'In what year was the Statue of Liberty dedicated?', a: 1886, year: true },
  { q: 'In what year was the Eiffel Tower completed?', a: 1889, year: true },
  { q: 'In what year were the first Nobel Prizes awarded?', a: 1901, year: true },
  { q: 'In what year AD was the Colosseum in Rome completed?', a: 80, year: true },
  { q: 'In what year did the Panama Canal open?', a: 1914, year: true },
  { q: 'In what year was Wolfgang Amadeus Mozart born?', a: 1756, year: true },
  { q: 'In what year did William Shakespeare die?', a: 1616, year: true },
  { q: 'The first crewed Moon landing was Apollo number…?', a: 11 },
  { q: 'In what year did the Channel Tunnel between England and France open?', a: 1994, year: true },
  { q: 'In what year did World War I begin?', a: 1914, year: true },

  // Geography
  { q: 'How many countries are members of the United Nations?', a: 193 },
  { q: 'How many countries are in the European Union (since 2020)?', a: 27 },
  { q: 'How tall is Mount Everest, in metres?', a: 8849, unit: 'm' },
  { q: 'How tall is the Burj Khalifa, in metres?', a: 828, unit: 'm' },
  { q: 'How many time zones does Russia span?', a: 11 },
  { q: 'How many countries are in Africa?', a: 54 },
  { q: 'How many cantons does Switzerland have?', a: 26 },
  { q: 'How many provinces does Canada have?', a: 10 },
  { q: 'How tall is Mount Kilimanjaro, in metres?', a: 5895, unit: 'm' },
  { q: 'How many official languages does the United Nations have?', a: 6 },
  { q: 'How many stripes are on the flag of the United States?', a: 13 },
  { q: 'How many states does Australia have (not counting territories)?', a: 6 },

  // Sports & games
  { q: 'How long is a marathon, in metres?', a: 42195, unit: 'm' },
  { q: 'How many squares are on a chessboard?', a: 64 },
  { q: 'What is the maximum break in snooker?', a: 147 },
  { q: 'What is a perfect score in ten-pin bowling?', a: 300 },
  { q: 'How many players does a rugby union team have on the field?', a: 15 },
  { q: 'In what year were the first modern Olympic Games held?', a: 1896, year: true },
  { q: 'In what year was the first FIFA World Cup held?', a: 1930, year: true },
  { q: 'What is the highest score possible with three darts?', a: 180 },
  { q: 'How many squares are on a Scrabble board?', a: 225 },
  { q: 'How many letter tiles are in a standard English Scrabble set?', a: 100 },
  { q: 'How many spaces are on a classic Monopoly board?', a: 40 },
  { q: 'How many dominoes are in a standard double-six set?', a: 28 },
  { q: "How many coloured stickers are on a classic 3×3 Rubik's Cube?", a: 54 },
  { q: 'How many cards are in a standard tarot deck?', a: 78 },
  { q: 'How many minutes long is a regulation NBA basketball game?', a: 48, unit: 'min' },
  { q: 'What is the total number of dots on a standard six-sided die?', a: 21 },
  { q: 'How many holes are played in a standard round of golf?', a: 18 },
  { q: 'How many pieces does each player start with in chess?', a: 16 },

  // Numbers & everyday
  { q: 'How many minutes are in a day?', a: 1440, unit: 'min' },
  { q: 'How many seconds are in a day?', a: 86400, unit: 's' },
  { q: 'How many hours are in a (non-leap) year?', a: 8760, unit: 'h' },
  { q: 'How many feet are in a mile?', a: 5280, unit: 'ft' },
  { q: 'How many yards are in a mile?', a: 1760, unit: 'yd' },
  { q: 'How many grams are in a pound (rounded)?', a: 454, unit: 'g' },
  { q: 'What is the sum of all the whole numbers from 1 to 100?', a: 5050 },
  { q: "How many items are in a 'gross'?", a: 144 },
  { q: 'How many years does a sesquicentennial celebrate?', a: 150, unit: 'years' },
  { q: 'How many keys are on a standard piano?', a: 88 },
  { q: 'What is 2 to the power of 10?', a: 1024 },
  { q: 'How many lines are in a sonnet?', a: 14 },
  { q: 'How many days are in a leap year?', a: 366, unit: 'days' },

  // Culture
  { q: 'In what year was the first iPhone released?', a: 2007, year: true },
  { q: "How many Oscars did the 1997 film 'Titanic' win?", a: 11 },
  { q: 'How many books are in the main Harry Potter series?', a: 7 },
  { q: 'In what year was the first Harry Potter book published?', a: 1997, year: true },
  { q: 'How many symphonies did Beethoven complete?', a: 9 },
  { q: 'In what year was Google founded?', a: 1998, year: true },
  { q: 'In what year was the first Star Wars film released?', a: 1977, year: true },
  { q: 'How many novels did Jane Austen complete?', a: 6 },
  { q: 'In what year did Tim Berners-Lee propose the World Wide Web?', a: 1989, year: true },
  { q: 'How many amendments does the US Constitution have?', a: 27 },
];
